# Generated by Django 2.1.5 on 2019-02-23 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('contenu', models.TextField()),
            ],
            options={
                'verbose_name': 'commentaire',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['date'], 'verbose_name': 'article'},
        ),
        migrations.AlterModelOptions(
            name='auteur',
            options={'verbose_name': 'auteur'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Titre',
            new_name='titre',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article'),
        ),
    ]
