# Generated by Django 2.1.5 on 2019-02-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190223_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='auteur',
            name='avatar',
            field=models.ImageField(default='fff', height_field=20, upload_to='avatar/', width_field=20),
        ),
    ]
